# This workflow will build a Java project with Gradle initially
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# another change by yy

name: Simple Pipe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: greetings-jar
        path: build/libs
  test-run:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download candidate artifacts
      uses: actions/download-artifact@v3       
      with:
        name: greetings-jar
    - shell: bash
      run: | 
        java -jar greetings-actions.jar ${{ github.event.inputs.myValues }} 
  
  count-args:
      
    runs-on: ubuntu-latest
    
    steps: 
    - id: report-count
      uses: yynetapp/arg-count-action@main
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }}
    - run: echo 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }} 
        exit 1
  
  create-issue-on-failure:

    runs-on: ubuntu-latest 
    needs: [test-run, count-args]
    if: always() && failure() 
    steps:
      - name: invoke workflow to create issue
        run: > 
          curl -X POST
          -H "authorization: Bearer ${{ secrets.WORKFLOW_USE }}"
          -H "Accept: application/vnd.github.v3+json"
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-failure-issue.yml/dispatches"
          -d '{"ref":"main",
               "inputs":
               {"title":"Automated workflow failure issue for commit ${{ github.sha }}",     
                "body":"This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"}
              }'    
